{
 "title": "Disk stats",
 "description": "Disk statistics for load, IOPS, pending operations and traffic",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   { "name": "host", "query": "SHOW TAG VALUES WITH KEY=host" },
   {
    "name": "device",
    "query": "SHOW TAG VALUES FROM \"disk_read\" WITH KEY = \"instance\""
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Load",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "alias": "load",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk_io_time",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) / 1000 FROM \"disk_io_time\" WHERE \"host\" =~ /^$host$/ AND \"instance\" =~ /^$device$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Disk load",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk_io_time",
     "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) / 1000 FROM \"disk_io_time\" WHERE \"host\" =~ /^$host$/ AND \"instance\" =~ /^$device$/ AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Pending Operations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Pending Operations",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk_value",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$device$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "pending_operations" }
     ]
    }
   ]
  },
  {
   "title": "IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk_read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "disk_ops" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "Write",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk_write",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "disk_ops" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Read",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk_read",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "disk_octets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$device$/" }
     ]
    },
    {
     "alias": "Write",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk_write",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "disk_octets" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$device$/" }
     ]
    }
   ]
  }
 ]
}